django_unchained/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^polls/', include('polls.urls', namespace="polls")),
    url(r'^madeit/', include('madeit.urls', namespace="madeit")),
    url(r'^admin/', include(admin.site.urls)),
]

madeit/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.ThreadView.as_view(), name='thread'),
    # url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

polls/urls.py
from django.conf.urls import url

from . import views

urlpatterns = [
    url(r'^$', views.IndexView.as_view(), name='index'),
    url(r'^(?P<pk>[0-9]+)/$', views.DetailView.as_view(), name='detail'),
    url(r'^(?P<pk>[0-9]+)/results/$', views.ResultsView.as_view(), name='results'),
    url(r'^(?P<question_id>[0-9]+)/vote/$', views.vote, name='vote'),
]

madeit/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Thread(models.Model):
    thread_title = models.CharField(max_length=200)
    thread_text = models.TextField(max_length=1000)
    pub_date = models.DateTimeField('date published')
    votes = models.IntegerField(default=0)
    user = models.CharField(max_length=32)
    
    def __str__(self):              # __unicode__ on Python 2
        return self.thread_text
        
    def was_published_recently(self):
        return self.pub_date >= timezone.now() - datetime.timedelta(days=1)
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Comment(models.Model):
    thread = models.ForeignKey(Thread)
    comment_text = models.TextField(max_length=1000)
    votes = models.IntegerField(default=0)
    pub_date = models.DateTimeField('date published')
    user = models.CharField(max_length=32)
    
    def __str__(self):              # __unicode__ on Python 2
        return self.comment_text

polls/models.py
import datetime

from django.db import models
from django.utils import timezone

# Create your models here.
class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')
    
    def __str__(self):              # __unicode__ on Python 2
        return self.question_text
        
    def was_published_recently(self):
        now = timezone.now()
        return now - datetime.timedelta(days=1) <= self.pub_date <= now
    
    was_published_recently.admin_order_field = 'pub_date'
    was_published_recently.boolean = True
    was_published_recently.short_description = 'Published recently?'


class Choice(models.Model):
    question = models.ForeignKey(Question)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)
    
    def __str__(self):              # __unicode__ on Python 2
        return self.choice_text

madeit/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic

from madeit.models import Comment, Thread


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'madeit/index.html'
    context_object_name = 'latest_thread_list'

    def get_queryset(self):
        """Return the last 10 published Threads."""
        return Thread.objects.order_by('-pub_date')[:10]


class ThreadView(generic.DetailView):
    model = Thread
    template_name = 'madeit/thread.html'

# def thread_vote(request, Thread_id):
#     p = get_object_or_404(Thread, pk=Thread_id)
#     try:
#         selected_Comment = p.Comment_set.get(pk=request.POST['Comment'])
#     except (KeyError, Comment.DoesNotExist):
#         # Redisplay the Thread voting form.
#         return render(request, 'madeit/thread.html', {
#             'Thread': p,
#             'error_message': "You didn't select a Comment.",
#         })
#     else:
#         selected_Comment.votes += 1
#         selected_Comment.save()
#         # Always return an HttpResponseRedirect after successfully dealing
#         # with POST data. This prevents data from being posted twice if a
#         # user hits the Back button.
#         return HttpResponseRedirect(reverse('madeit:results', args=(p.id,)))
        

polls/views.py
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponseRedirect
from django.core.urlresolvers import reverse
from django.views import generic
from django.utils import timezone

from polls.models import Choice, Question


# Create your views here.
class IndexView(generic.ListView):
    template_name = 'polls/index.html'
    context_object_name = 'latest_question_list'

    def get_queryset(self):
        """Return the last five published questions."""
        return Question.objects.filter(pub_date__lte=timezone.now()).order_by('-pub_date')[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = 'polls/detail.html'
    
    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Question.objects.filter(pub_date__lte=timezone.now())


class ResultsView(generic.DetailView):
    model = Question
    template_name = 'polls/results.html'

def vote(request, question_id):
    p = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = p.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'polls/detail.html', {
            'question': p,
            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('polls:results', args=(p.id,)))

madeit/templates/madeit/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'madeit/style.css' %}" />


<h1><a  class="madeit" href="{% url 'madeit:index' %}">MadeIt</a></h1> {% if latest_thread_list %}

<table class="thread_preview">
    {% for thread in latest_thread_list %}
    <tr>
        <td>
            <div class="votes">
                <p><button class="upvote" type="button>">^</button></p>
                <p>{{ thread.votes }}</p>
                <p><button class="downvote" type="button>">v</button></p>
            </div>
        </td>
        <td>
            <p>{{ thread.thread_title }}</p>
            <p class="meta">posted by {{ thread.user }} at {{ thread.pub_date }} | <a href="{% url 'madeit:thread' thread.id %}">[comments]</a></p>
        </td>
    </tr>

    {% endfor %}
</table>

{% else %}
<p>There doesn't appear to be any threads here.</p>
{% endif %}

madeit/templates/madeit/thread.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'madeit/style.css' %}" />

<h1><a class="madeit" href="{% url 'madeit:index' %}">MadeIt</a></h1>

<table class="thread_full">
    <tr>
        <td>
            <div class="votes">
                <p><button class="upvote" type="button>">^</button></p>
                <p>{{ thread.votes }}</p>
                <p><button class="downvote" type="button>">v</button></p>
            </div>
        </td>
        <td>
            <h2>{{ thread.thread_title }}</h2>
            <p>{{ thread.thread_text }}</p>
            <p class="meta">posted by {{ thread.user }} at {{ thread.pub_date }}</p>
        </td>
    </tr>
</table>


<br>
<p class="subtitle">Comments:</p>

{% if thread.comment_set.all %}


<table class="comment">
    {% for comment in thread.comment_set.all %}
    <tr>
        <td>
            <div class="votes">
                <p><button class="upvote" type="button>">^</button></p>
                <p>{{ comment.votes }}</p>
                <p><button class="downvote" type="button>">v</button></p>
            </div>
        </td>
        <td>
            <p>{{ comment.comment_text }}</p>
            <p class="meta">posted by {{ thread.user }} at {{ comment.pub_date }}</p>
        </td>
    </tr>
    {% endfor %}
</table>


{% else %}
<p class="meta">There doesn't appear to be any comments here.</p>
{% endif %}

polls/templates/polls/index.html
{% load staticfiles %}

<link rel="stylesheet" type="text/css" href="{% static 'polls/style.css' %}" />

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}